### PR TITLE
Bump k3d and harvester version

### PR DESCRIPTION
**Pull request by orangedeng**
Related issue: https://github.com/cnrancher/autok3s/issues/512

### CODE REVIEW

**Review by JacieChao — APPROVED** [review]
LGTM
Merge after dev test

**Comment by orangedeng** [comment]
k3d test passed

**Comment by Jason-ZW** [comment]
LGTM

**Comment by orangedeng** [comment]
Failed to build windows binary, as following:

```
[INFO] [1227 06:45:43] building windows/amd64
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
go: downloading github.com/Microsoft/go-winio v0.5.2
go: downloading github.com/Microsoft/hcsshim v0.9.4
# github.com/c9s/goprocinfo/linux
/go/pkg/mod/github.com/c9s/goprocinfo@v0.0.0-20210130143923-c95fcf8c64a8/linux/disk.go:15:16: undefined: syscall.Statfs_t
/go/pkg/mod/github.com/c9s/goprocinfo@v0.0.0-20210130143923-c95fcf8c64a8/linux/disk.go:16:17: undefined: syscall.Statfs
[FATA] [1227 06:48:16] hack/make-rules/autok3s.sh:115 'GOOS=${os} GOARCH=${arch} CGO_ENABLED=0 go build -ldflags "${version_flags} ${flags} ${ext_flags}" -tags netgo,prod -o "${CURR_DIR}/bin/${platform}/autok3s${suffix}" "${CURR_DIR}/main.go"' exited with status 2
```

After upgraded to harvester v1.1.1, the dependency `github.com/c9s/goprocinfo/linux`, which doesn't support windows platform, is introduced into autok3s. closing this PR for now

**Pull request closed without merging**
